name: json

on: [push]

jobs:   
    predeploy:
       runs-on: ubuntu-latest
        steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      
      -name: 'pre-deployment'
       id: pre-deployment
       uses: ./.github/actions/hello-world-action/
       with:
          tla:- ${{ github.event.input.TLA }}
      - run: echo "hello world"    
      
